### PR TITLE
Fixed issue #1

### PR DESCRIPTION
**Pull request by EggieCode**
Fixed issue #1

### CODE REVIEW

**Comment by stejoo** [comment]
I made a issue1 branch to work on this issue, instead of working in the master branch. I want master to be always usable and ready for deployment.

Remarks:
- `defaults/main.yml`: 
1. Use of a .ini file should be optional. To make it that way please include a switch in the `defaults/main.yml` which defaults to false, like: `use_ini_file=no`. 
2. The default variable list `teamspeak_ini` looks alright, but is not in line with the TeamSpeak 3 Server defaults. Have a look at the [TeamSpeak 3 Server Quick Start](http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Quick%20Start.txt). For example `logpath` has a default of "logs/", not "/var/log/teamspeak3-server". 
- `tasks/config.yml`:
1. I don't see the use of defining `ts3server_dir` if you are just using it once. I don't see you using it elsewhere.
- `tasks/main.yml`: looks alright.
1. Swap the when-statement check for the `use_ini_file` switch here? As `teamspeak_ini` will always be defined if it exists in the `defaults/main.yml'.
- `templates/teamspeak3-server.service.j2`:
1. `teamspeak.ini_file` seems undefined. 
2. The if statement should be changed to check for the `use_ini_file` being true. Because `teamspeak_ini` will always be defined when you place it in the `defaults/main.yml`.
- `templates/ts3server.ini.j2`
1. Looks OK. Perhaps skip writing the `machine_id` line if it's empty anyway.

**Comment by EggieCode** [comment]
> Use of a .ini file should be optional. To make it that way please include a switch in the defaults/main.yml which defaults to false, like: use_ini_file=no. 

Possible, but if teamspeak.ini_file is not defined or none it will not run the config.yml

> For example logpath has a default of "logs/", not "/var/log/teamspeak3-server". 

Copy paste from my config and it look need.

> I don't see the use of defining ts3server_dir if you are just using it once. I don't see you using it elsewhere.

Copy paste from previous commits. It keep it clean for upcomming issues.

> Swap the when-statement check for the use_ini_file switch here? As teamspeak_ini will always be defined if it exists in the `defaults/main.yml'.

Same as the top one.

> teamspeak.ini_file seems undefined. 

Failure. Forgot to add it.

> Perhaps skip writing the machine_id line if it's empty anyway.

Read the manual.

**Comment by EggieCode** [comment]
Problem: ansible relative paths

> For example logpath has a default of "logs/", not "/var/log/teamspeak3-server". 

Ansible cannot change that relative paths from logs ('logs/') to absoulte path. So for new I lave it in the /var/log/teamspeak3-server

Rest of the "problems" solved.

**Comment by stejoo** [comment]
> Possible, but if teamspeak.ini_file is not defined or none it will not run the config.yml

That's the problem: it is defined in defaults. That's why the "if teamspeak_ini is defined" will always return true. The file `defaults/main.yml` is for settings defaults, not changing variables. It should never be changed, only overridden else where. That's why I asked for a yes/no switch, which defaults to off. And can be overridden using host/group/extra vars, that take preference over defaults.

> Copy paste from my config and it look need.

But it's not the default, and therefor should not be defined globally as such. The default is "logs/". If you want to have "/var/log/teamspeak3-server" yourself, that's totally fine. But overrule it on your end, not in the global defaults.
Creating the logpath is a good addition to the tasks. :)

> Read the manual.

I did. Don't understand what you mean with that comment. I noticed the `machine_id` may be empty. My suggestion was leaving it out all together if it is. But it doesn't really matter.

> Ansible cannot change that relative paths from logs ('logs/') to absoulte path.

You can leave it empty by default. Only run a task creating a directory if the `logpath` is not empty, and do the same with the configuration of the logpath in the ini file. That way it will default to "logs/", yet change it to something else when you want it to.

I'll have a go at this issue myself tomorrow. See if the code can clear things up.

**Comment by EggieCode** [comment]
> I did. Don't understand what you mean with that comment. I noticed the machine_id may be empty. My suggestion was leaving it out all together if it is. But it doesn't really matter.

The manual: 
`Optional name of this server process to identify a group of servers with
  the same ID. This can be useful when running multiple TeamSpeak 3 Server
  instances on the same database. Please note that we strongly recommend that
  you do NOT run multiple server instances on the same SQLite database.
  Default: The server instance will not use a machine ID.`
That states the it is used to run multiple teamspeak servers on the same database.
It is usefull, maybe not for you.

> That's the problem: it is defined in defaults. 

See commit.

> Ansible cannot change that relative paths from logs ('logs/') to absoulte path.

Fix if you want to.

**Comment by stejoo** [comment]
Merging this into the issue1 branch. Thank you.

**Pull request merged**
